### ISSUE TITLE
Monitor_4char problem and question

### ISSUE THREAD

**Issue by MOARdV** [Alexustas/Props-requests#39]
I have been using the Monitor_4char for a long time, but I wanted to switch to the copy that is in the ASET props dev build.  However, when I try to use that prop, it does not appear in the game, but I see it in Unity.

The older version I have from when you created it works.

I have not checked Monitor_8char yet.

Also, a question: is it possible to put a transform on the props so I can use JSILabel instead of RasterPropMonitor to display text?  I tried to use the screen transform MonitorScreen04, but the text is small and pointed the wrong way.

**Comment by Alexustas** [comment]
I have not updated these props since I made them for you

I suggest you use another type of indicator - 'DigitalIndicator_EmissiveScreen' (_\GameData\ASET\ASET_Props\Instruments\DigitalIndicator_EmissiveScreen_)
![2016-08-11 02-57-35-872](https://cloud.githubusercontent.com/assets/6713671/17570816/c24bb71a-5f6f-11e6-8bf1-77571ea7f7aa.jpg) 
![2016-08-11 02-56-25-034](https://cloud.githubusercontent.com/assets/6713671/17570834/cf84a0e0-5f6f-11e6-8915-3924eba990ee.jpg)
![2016-08-11 02-56-01-477](https://cloud.githubusercontent.com/assets/6713671/17570836/d1abb9a8-5f6f-11e6-9f76-5024e461d3aa.jpg)

This prop is fully customizable, so you can give it a look of the old LСD display

![2016-08-11 02-54-16-287](https://cloud.githubusercontent.com/assets/6713671/17570985/56259546-5f70-11e6-81b5-608f6cccab14.jpg)
![2016-08-11 02-54-48-528](https://cloud.githubusercontent.com/assets/6713671/17570989/57ff8c14-5f70-11e6-9e17-4470cea31df7.jpg)

but there is one problem. Now this display is only available for 3,4,5 and 6 characters. Of course, I can add models for 7 and 8 characters, if you need to

**Comment by MOARdV** [comment]
> but there is one problem. Now this display is only available for 3,4,5 and 6 characters. Of course, I can add models for 7 and 8 characters, if you need to

Right now, I am using 4 characters only.  I will try that one instead.

**Comment by MOARdV** [comment]
Closing this, since you answered my question.
